#!/usr/bin/env sh

#ddev-generated
## Description: Run redis-cli inside the Redis cluster (connects to node-1)
## Usage: redis-cli [flags] [args]
## Example: "ddev redis-cli KEYS *" or "ddev redis-cli CLUSTER INFO" or "ddev redis-cli --version"
## Aliases: redis

if [ -f /etc/redis/conf/security.conf ]; then
  redis-cli -c -p 7001 -h redis-node-1 -a redis --no-auth-warning $@
else
  redis-cli -c -p 7001 -h redis-node-1 $@
fi
